const actions = {
    CART_ADDED: "CART_ITEM_ADDED",
    CART_REMOVED: "CART_ITEM_REMOVED",
    CART_REMOVED_ALL: "CART_ITEM_REMOVED_ALL",
    CART_ITEM_INCREASE: "CART_ITEM_INCREASE",
    CART_ITEM_DECREASE: "CART_ITEM_DECREASE",
  };
  
  export { actions };